import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('fs', () => ({
  writeFileSync: vi.fn(),
  readFileSync: vi.fn(),
  existsSync: vi.fn(),
}));

vi.mock('../src/claude.js', () => ({
  runPrompt: vi.fn(),
}));

import { createLoggerMock } from './helpers/mocks.js';

vi.mock('../src/logger.js', () => createLoggerMock());

vi.mock('../src/executor.js', () => ({
  SAFETY_PREAMBLE: 'MOCK_PREAMBLE\n',
}));

vi.mock('../src/prompts/loader.js', () => ({
  CONSOLIDATION_PROMPT: 'Mock consolidation prompt template with Critical High Medium Low tiers and consolidated, prioritized action plan instructions.',
}));

vi.mock('../src/report.js', () => ({
  getVersion: vi.fn(() => '1.2.3'),
}));

import { writeFileSync } from 'fs';
import { runPrompt } from '../src/claude.js';
import { info, warn } from '../src/logger.js';
import { buildConsolidationPrompt, generateActionPlan, ACTIONS_FILENAME } from '../src/consolidation.js';
import { makeResults } from './helpers/testdata.js';

beforeEach(() => {
  vi.clearAllMocks();
});

describe('buildConsolidationPrompt', () => {
  it('includes step output sections for completed steps', () => {
    const results = makeResults({ completedCount: 2, failedCount: 0 });
    results.results[0].output = 'Found unused imports in app.js';
    results.results[1].output = 'Refactored auth module';

    const prompt = buildConsolidationPrompt(results);

    expect(prompt).toContain('### Step 1: Step1 (completed)');
    expect(prompt).toContain('Found unused imports in app.js');
    expect(prompt).toContain('### Step 2: Step2 (completed)');
    expect(prompt).toContain('Refactored auth module');
  });

  it('shows "No output (step failed)" for failed steps', () => {
    const results = makeResults({ completedCount: 1, failedCount: 1 });

    const prompt = buildConsolidationPrompt(results);

    expect(prompt).toContain('### Step 2: FailStep1 (failed)');
    expect(prompt).toContain('No output (step failed)');
  });

  it('truncates outputs exceeding 6000 chars', () => {
    const results = makeResults({ completedCount: 1, failedCount: 0 });
    results.results[0].output = 'x'.repeat(7000);

    const prompt = buildConsolidationPrompt(results);

    expect(prompt).toContain('x'.repeat(6000));
    expect(prompt).toContain('[...truncated');
    expect(prompt).not.toContain('x'.repeat(6001));
  });

  it('passes through outputs under 6000 chars unchanged', () => {
    const results = makeResults({ completedCount: 1, failedCount: 0 });
    results.results[0].output = 'short output';

    const prompt = buildConsolidationPrompt(results);

    expect(prompt).toContain('short output');
    expect(prompt).not.toContain('[...truncated');
  });

  it('handles empty results array', () => {
    const results = { results: [], completedCount: 0, failedCount: 0 };

    const prompt = buildConsolidationPrompt(results);

    // Should still include the consolidation prompt template text
    expect(prompt).toContain('consolidated, prioritized action plan');
  });

  it('includes the consolidation prompt template text', () => {
    const results = makeResults({ completedCount: 1, failedCount: 0 });

    const prompt = buildConsolidationPrompt(results);

    expect(prompt).toContain('consolidated, prioritized action plan');
    expect(prompt).toContain('Critical');
    expect(prompt).toContain('High');
    expect(prompt).toContain('Medium');
    expect(prompt).toContain('Low');
  });

  it('handles null/undefined output gracefully', () => {
    const results = makeResults({ completedCount: 1, failedCount: 0 });
    results.results[0].output = null;

    const prompt = buildConsolidationPrompt(results);

    // null output for completed step should render as empty (truncateOutput returns '')
    expect(prompt).toContain('### Step 1: Step1 (completed)');
    expect(prompt).not.toContain('No output (step failed)');
  });
});

describe('generateActionPlan', () => {
  it('returns action plan content on successful Claude response', async () => {
    runPrompt.mockResolvedValue({
      success: true,
      output: '# NightyTidy Action Plan\n\n## Critical\n\nNo items.',
    });

    const results = makeResults({ completedCount: 2, failedCount: 0 });
    const content = await generateActionPlan(results, '/fake/project', {});

    expect(content).toContain('# NightyTidy Action Plan');
    expect(content).toContain('Generated by NightyTidy');
  });

  it('writes NIGHTYTIDY-ACTIONS.md to the correct path', async () => {
    runPrompt.mockResolvedValue({
      success: true,
      output: '# Action Plan',
    });

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    await generateActionPlan(results, '/fake/project', {});

    expect(writeFileSync).toHaveBeenCalledWith(
      expect.stringContaining('NIGHTYTIDY-ACTIONS.md'),
      expect.stringContaining('# Action Plan'),
      'utf8'
    );
  });

  it('returns null when Claude returns failure', async () => {
    runPrompt.mockResolvedValue({ success: false, output: '', error: 'timeout' });

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    const content = await generateActionPlan(results, '/fake/project', {});

    expect(content).toBeNull();
    expect(warn).toHaveBeenCalledWith(expect.stringContaining('failed'));
    expect(writeFileSync).not.toHaveBeenCalled();
  });

  it('returns null when Claude returns empty output', async () => {
    runPrompt.mockResolvedValue({ success: true, output: '   ' });

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    const content = await generateActionPlan(results, '/fake/project', {});

    expect(content).toBeNull();
  });

  it('skips Claude call when completedCount is 0', async () => {
    const results = makeResults({ completedCount: 0, failedCount: 3 });
    const content = await generateActionPlan(results, '/fake/project', {});

    expect(content).toBeNull();
    expect(runPrompt).not.toHaveBeenCalled();
    expect(info).toHaveBeenCalledWith(expect.stringContaining('no steps completed'));
  });

  it('passes timeout option through to runPrompt', async () => {
    runPrompt.mockResolvedValue({ success: true, output: '# Plan' });

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    await generateActionPlan(results, '/fake/project', { timeout: 3600000 });

    expect(runPrompt).toHaveBeenCalledWith(
      expect.any(String),
      '/fake/project',
      expect.objectContaining({ timeout: 3600000 })
    );
  });

  it('returns null and warns on thrown error (never throws)', async () => {
    runPrompt.mockRejectedValue(new Error('network failure'));

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    const content = await generateActionPlan(results, '/fake/project', {});

    expect(content).toBeNull();
    expect(warn).toHaveBeenCalledWith(expect.stringContaining('network failure'));
  });

  it('includes version footer in written file', async () => {
    runPrompt.mockResolvedValue({ success: true, output: '# Plan content' });

    const results = makeResults({ completedCount: 1, failedCount: 0 });
    await generateActionPlan(results, '/fake/project', {});

    const writtenContent = writeFileSync.mock.calls[0][1];
    expect(writtenContent).toMatch(/Generated by NightyTidy v1\.2\.3/);
  });

  it('exports ACTIONS_FILENAME constant', () => {
    expect(ACTIONS_FILENAME).toBe('NIGHTYTIDY-ACTIONS.md');
  });
});
