import { writeFileSync } from 'fs';
import path from 'path';
import { runPrompt } from './claude.js';
import { info, warn } from './logger.js';
import { SAFETY_PREAMBLE } from './executor.js';
import { CONSOLIDATION_PROMPT } from './prompts/loader.js';
import { getVersion } from './report.js';

const OUTPUT_TRUNCATE_LIMIT = 6000;
export const ACTIONS_FILENAME = 'NIGHTYTIDY-ACTIONS.md';

function truncateOutput(text, limit = OUTPUT_TRUNCATE_LIMIT) {
  if (!text || text.length <= limit) return text || '';
  return text.slice(0, limit) + '\n\n[...truncated — full output in run log]';
}

function buildStepOutputsSection(results) {
  const sections = [];
  for (const r of results) {
    const status = r.status === 'completed' ? 'completed' : 'failed';
    const output = r.status === 'completed'
      ? truncateOutput(r.output)
      : 'No output (step failed)';
    sections.push(
      `### Step ${r.step.number}: ${r.step.name} (${status})\n${output}\n---`
    );
  }
  return sections.join('\n\n');
}

export function buildConsolidationPrompt(executionResults) {
  const stepOutputs = buildStepOutputsSection(executionResults.results);
  return stepOutputs + '\n\n' + CONSOLIDATION_PROMPT;
}

export async function generateActionPlan(executionResults, projectDir, { timeout } = {}) {
  if (executionResults.completedCount === 0) {
    info('Skipping action plan — no steps completed');
    return null;
  }

  try {
    const prompt = SAFETY_PREAMBLE + buildConsolidationPrompt(executionResults);
    info('Generating consolidated action plan...');

    const result = await runPrompt(prompt, projectDir, {
      label: 'Consolidation action plan',
      timeout,
    });

    if (!result.success || !result.output?.trim()) {
      warn('Action plan generation failed — NIGHTYTIDY-ACTIONS.md will not be created. NIGHTYTIDY-REPORT.md is still available.');
      return null;
    }

    const actionsPath = path.join(projectDir, ACTIONS_FILENAME);
    const content = result.output.trim() + `\n\n---\n*Generated by NightyTidy v${getVersion()}*\n`;
    writeFileSync(actionsPath, content, 'utf8');
    info(`Action plan written to ${actionsPath}`);

    return content;
  } catch (err) {
    warn(`Action plan generation error (${err.message}) — NIGHTYTIDY-ACTIONS.md will not be created.`);
    return null;
  }
}
