import { writeFileSync, readFileSync, existsSync } from 'fs';
import path from 'path';
import { info, warn } from './logger.js';

let cachedVersion;

export function getVersion() {
  if (cachedVersion) return cachedVersion;
  try {
    const pkgPath = new URL('../package.json', import.meta.url);
    cachedVersion = JSON.parse(readFileSync(pkgPath, 'utf8')).version;
  } catch {
    cachedVersion = '0.1.0';
  }
  return cachedVersion;
}

export function formatDuration(ms) {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (hours > 0) {
    return `${hours}h ${String(minutes % 60).padStart(2, '0')}m`;
  }
  return `${minutes}m ${String(seconds % 60).padStart(2, '0')}s`;
}

function fallbackNarration(results) {
  return (
    `NightyTidy ran ${results.completedCount + results.failedCount} improvement steps on your codebase. ` +
    `${results.completedCount} steps completed successfully. ` +
    `See the step results below for details on what changed. The detailed changelog couldn't ` +
    `be generated this time \u2014 check nightytidy-run.log for more information.`
  );
}

function buildSummarySection(results, metadata) {
  const date = new Date(metadata.startTime).toISOString().split('T')[0];
  const duration = formatDuration(metadata.endTime - metadata.startTime);
  const total = results.completedCount + results.failedCount;

  return (
    `## Run Summary\n\n` +
    `- **Date**: ${date}\n` +
    `- **Duration**: ${duration}\n` +
    `- **Steps completed**: ${results.completedCount}/${total}\n` +
    `- **Steps failed**: ${results.failedCount}\n` +
    `- **Branch**: ${metadata.branchName}\n` +
    `- **Safety tag**: ${metadata.tagName}\n\n`
  );
}

function buildStepTable(results) {
  let table = `## Step Results\n\n`;
  table += `| # | Step | Status | Duration | Attempts |\n`;
  table += `|---|------|--------|----------|----------|\n`;

  for (const r of results.results) {
    const status = r.status === 'completed' ? '\u2705 Completed' : '\u274C Failed';
    const duration = formatDuration(r.duration);
    table += `| ${r.step.number} | ${r.step.name} | ${status} | ${duration} | ${r.attempts} |\n`;
  }

  return table + '\n';
}

function buildFailedSection(results) {
  let section = `## Failed Steps\n\n`;

  for (const r of results.results) {
    if (r.status !== 'failed') continue;
    section += `### Step ${r.step.number}: ${r.step.name}\n`;
    section += `- **Error**: ${r.error || 'Unknown error'}\n`;
    section += `- **Attempts**: ${r.attempts} (1 initial + ${r.attempts - 1} retries)\n`;
    section += `- **Suggestion**: Try running this step individually later with \`nightytidy\` and selecting only this step.\n\n`;
  }

  return section;
}

function buildUndoSection(metadata) {
  return (
    `## How to Undo This Run\n\n` +
    `If you need to reverse all changes from this run, ask Claude Code:\n\n` +
    `> "Reset my project to the git tag \`${metadata.tagName}\`"\n\n` +
    `Or run this git command:\n\n` +
    `\`\`\`\n` +
    `git reset --hard ${metadata.tagName}\n` +
    `\`\`\`\n\n` +
    `The NightyTidy branch \`${metadata.branchName}\` is preserved and can be deleted manually when no longer needed.\n\n` +
    `---\n*Generated by NightyTidy v${getVersion()}*\n`
  );
}

export function generateReport(results, narration, metadata) {
  const date = new Date(metadata.startTime).toISOString().split('T')[0];

  let report = `# NightyTidy Report \u2014 ${date}\n\n`;

  if (narration) {
    report += `${narration}\n\n---\n\n`;
  } else {
    report += `${fallbackNarration(results)}\n\n---\n\n`;
  }

  report += buildSummarySection(results, metadata);
  report += buildStepTable(results);

  if (results.failedCount > 0) {
    report += buildFailedSection(results);
  }

  report += buildUndoSection(metadata);

  const reportPath = path.join(metadata.projectDir, 'NIGHTYTIDY-REPORT.md');
  writeFileSync(reportPath, report, 'utf8');
  info(`Report written to ${reportPath}`);

  // Update CLAUDE.md
  updateClaudeMd(metadata);
}

function updateClaudeMd(metadata) {
  const claudePath = path.join(metadata.projectDir, 'CLAUDE.md');
  const date = new Date(metadata.startTime).toISOString().split('T')[0];
  const section =
    `\n## NightyTidy \u2014 Last Run\n\n` +
    `Last run: ${date}. To undo, reset to git tag \`${metadata.tagName}\`.\n`;

  try {
    if (existsSync(claudePath)) {
      let content = readFileSync(claudePath, 'utf8');
      const marker = '## NightyTidy';
      const markerIndex = content.indexOf(marker);

      if (markerIndex !== -1) {
        // Find the end of this section (next ## or end of file)
        const nextSection = content.indexOf('\n## ', markerIndex + marker.length);
        if (nextSection !== -1) {
          content = content.slice(0, markerIndex) + section.trim() + '\n' + content.slice(nextSection);
        } else {
          content = content.slice(0, markerIndex) + section.trim() + '\n';
        }
      } else {
        content += section;
      }

      writeFileSync(claudePath, content, 'utf8');
    } else {
      writeFileSync(claudePath, section.trim() + '\n', 'utf8');
    }
    info('CLAUDE.md updated with NightyTidy run info');
  } catch (err) {
    warn(`Failed to update CLAUDE.md: ${err.message}`);
  }
}
